# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e13a194d420a2bce35cf64ac725b3daf1e6bc5978dd3443970a875cf69cb2d52081951e09dd84a81822bcf1ad45a34235e24c55fc52080050949ab201a5a1ef

test:
  secret_key_base: 5d0a137e383d4c2fb609fc277ba593da634195a4c7f3de7773845697c59f2d62537941b87b501eb08b669f4ecaa1d9d0f2f39cad804a07f1424f89ef84643989

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
